#!/bin/bash
#set -e
##################################################################################################################
# Author 	: Erik Dubois
# Website   : https://www.erikdubois.be
# Website   : https://www.alci.online
# Website	: https://www.arcolinux.info
# Website	: https://www.arcolinux.com
# Website	: https://www.arcolinuxd.com
# Website	: https://www.arcolinuxb.com
# Website	: https://www.arcolinuxiso.com
# Website	: https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
#tput setaf 0 = black 
#tput setaf 1 = red 
#tput setaf 2 = green
#tput setaf 3 = yellow 
#tput setaf 4 = dark blue 
#tput setaf 5 = purple
#tput setaf 6 = cyan 
#tput setaf 7 = gray 
#tput setaf 8 = light blue
##################################################################################################################

echo "###############################################################################"
echo "Removing the pacman databases at /var/lib/pacman/sync/*"
echo "###############################################################################"
echo
sudo rm /var/lib/pacman/sync/*
echo

echo "###############################################################################"
echo "Removing /etc/pacman.d/gnupg folder"
echo "###############################################################################"
echo
sudo rm -rf /etc/pacman.d/gnupg/*
echo

echo "###############################################################################"
echo "Initialize pacman keys with pacman-key --init"
echo "###############################################################################"
echo
sudo pacman-key --init
echo

echo "###############################################################################"
echo "Populating keyring with pacman-key --populate"
echo "###############################################################################"
echo 
sudo pacman-key --populate
echo

echo "###############################################################################"
echo "Adding Ubuntu keyserver to /etc/pacman.d/gnupg/gpg.conf"
echo "###############################################################################"
echo 
echo "
keyserver hkp://keyserver.ubuntu.com:80" | sudo tee --append /etc/pacman.d/gnupg/gpg.conf

echo
echo "###############################################################################"
echo "Getting new databases with pacman -Sy"
echo "###############################################################################"
echo 
sudo pacman -Sy
echo

echo "###############################################################################"
echo "###                DONE - YOU CAN CLOSE THIS WINDOW                        ####"
echo "###############################################################################"